version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:18.1'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgresuser1
      POSTGRES_PASSWORD: user1password
      POSTGRES_DB: vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
